workflows:
  android-build:
    name: Build BLE Notifier APK
    max_build_duration: 30
    environment:
      vars:
        PACKAGE_NAME: "com.example.blenotification"
      android_signing:
        - ble_key
      java: 17
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/debug/app-debug.apk
